### ISSUE TITLE
test more close to reality as possible

### ISSUE THREAD

**Issue by cri5ti** [cri5ti/ippppp#25]
I think we should have tests more close to reality as possible. With mocked data not only there's a maintenance cost (every time there's a model change we will have to recreate it) but it could potentially increase the tests permissiveness (since they aren't being executed with real data). In other words I think is safer to test with real data, let me know whats your opinion 👍

Apart of component testing, shouldn't the tests include the api calls in its scope? I've also seen on Jest documentation they mock the api calls but doing that aren't we skipping testing an important functionality of the application?

Please educate me @cri5ti ✌

_Originally posted by @jjtfsalgado in https://github.com/cri5ti/ippppp/diffs_

**Comment by cri5ti** [comment]
There are 2 types of tests: 
 * unit tests ( unit / components): test just the unit, in isolation. 
 * integration tests: test how several units / components integrate together.

Sure, there's the downside of maintaining your mocks, but otherwise you have many other complexities you have to worry about:
 * was the error in the backend (other component?)
 * was the right version of backend deployed?
 * do I have the right url of the backend?
 * did I seed the right data before? 
 * it's not easy to add all edge cases when you have to consider all the layers of your app
 * my test worked fine in summer, but in winter it fals 🙃

I would suggest unit tests for components that have some complexity in them.
E.g. a calendar component would be a great example.

A few post depoloyment integration tests could capture some other kinds of bugs. We could achieve this by browser automation, running through a few steps.

**Comment by jjtfsalgado** [comment]
Thanks! 😉
