### ISSUE TITLE
Investigate database storage options

### ISSUE THREAD

**Issue by cri5ti** [cri5ti/ippppp#6]

**Comment by gomesp80** [comment]
If we are thinking on using Azure, we have:
- Azure table storage (cheapest)
- Cosmos DB (fastest / scalable)
- SQL Server (familiar and business relevant)
- MySQL / PostgreSQL (bigger learning curve and not native) 
- SQLite (not sure it is a good idea)

**Comment by jjtfsalgado** [comment]
Could we go for SQL Server plzzzz 😻?

**Comment by cri5ti** [comment]
SQL Server coming in #10 

I'd still like to try out CosmosDb at some point for the realtime stuff.

**Comment by gomesp80** [comment]
At some point, probably on a different project, but for now I would stick with the easy.
